"""Initial schema 24 tables

Revision ID: 8949ecbd623b
Revises: 
Create Date: 2026-09-16 16:17:46.023858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8949ecbd623b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corridors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('division', sa.String(length=50), nullable=False),
    sa.Column('start_station', sa.String(length=10), nullable=False),
    sa.Column('end_station', sa.String(length=10), nullable=False),
    sa.Column('total_distance_km', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corridors_code'), 'corridors', ['code'], unique=True)
    op.create_index(op.f('ix_corridors_id'), 'corridors', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('integration_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=20), nullable=False),
    sa.Column('sync_type', sa.String(length=30), nullable=True),
    sa.Column('records_synced', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_logs_id'), 'integration_logs', ['id'], unique=False)
    op.create_index(op.f('ix_integration_logs_status'), 'integration_logs', ['status'], unique=False)
    op.create_index(op.f('ix_integration_logs_system_name'), 'integration_logs', ['system_name'], unique=False)
    op.create_index(op.f('ix_integration_logs_timestamp'), 'integration_logs', ['timestamp'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('trains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_no', sa.String(length=10), nullable=False),
    sa.Column('train_name', sa.String(length=100), nullable=False),
    sa.Column('train_type', sa.String(length=30), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=True),
    sa.Column('max_speed', sa.Integer(), nullable=True),
    sa.Column('is_freight', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    op.create_index(op.f('ix_trains_is_freight'), 'trains', ['is_freight'], unique=False)
    op.create_index(op.f('ix_trains_priority_level'), 'trains', ['priority_level'], unique=False)
    op.create_index(op.f('ix_trains_train_no'), 'trains', ['train_no'], unique=True)
    op.create_table('railway_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corridor_id', sa.Integer(), nullable=False),
    sa.Column('section_code', sa.String(length=30), nullable=False),
    sa.Column('start_station', sa.String(length=10), nullable=False),
    sa.Column('end_station', sa.String(length=10), nullable=False),
    sa.Column('track_type', sa.String(length=20), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=False),
    sa.Column('max_permissible_speed', sa.Integer(), nullable=True),
    sa.Column('line_capacity', sa.Integer(), nullable=True),
    sa.Column('current_traffic_density', sa.Float(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lng', sa.Float(), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lng', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['corridor_id'], ['corridors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_railway_sections_id'), 'railway_sections', ['id'], unique=False)
    op.create_index(op.f('ix_railway_sections_section_code'), 'railway_sections', ['section_code'], unique=True)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_code', sa.String(length=50), nullable=False),
    sa.Column('resource_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('base_station', sa.String(length=10), nullable=False),
    sa.Column('availability_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_availability_status'), 'resources', ['availability_status'], unique=False)
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_resource_code'), 'resources', ['resource_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['railway_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_code', sa.String(length=50), nullable=False),
    sa.Column('asset_name', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('km_location', sa.Float(), nullable=False),
    sa.Column('installation_date', sa.DateTime(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['railway_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('change_details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('block_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('horizon_start', sa.DateTime(), nullable=False),
    sa.Column('horizon_end', sa.DateTime(), nullable=False),
    sa.Column('total_blocks', sa.Integer(), nullable=True),
    sa.Column('total_delay_impact_minutes', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_plans_id'), 'block_plans', ['id'], unique=False)
    op.create_index(op.f('ix_block_plans_plan_code'), 'block_plans', ['plan_code'], unique=True)
    op.create_index(op.f('ix_block_plans_status'), 'block_plans', ['status'], unique=False)
    op.create_table('train_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_entry_time', sa.DateTime(), nullable=False),
    sa.Column('scheduled_exit_time', sa.DateTime(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('halt_station', sa.String(length=10), nullable=True),
    sa.Column('halt_duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['railway_sections.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_schedules_id'), 'train_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_train_schedules_scheduled_entry_time'), 'train_schedules', ['scheduled_entry_time'], unique=False)
    op.create_index(op.f('ix_train_schedules_scheduled_exit_time'), 'train_schedules', ['scheduled_exit_time'], unique=False)
    op.create_table('asset_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_by', sa.String(length=100), nullable=False),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_history_id'), 'asset_history', ['id'], unique=False)
    op.create_index(op.f('ix_asset_history_recorded_at'), 'asset_history', ['recorded_at'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_code', sa.String(length=50), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=30), nullable=False),
    sa.Column('requested_start_time', sa.DateTime(), nullable=False),
    sa.Column('requested_end_time', sa.DateTime(), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('lead_department_id', sa.Integer(), nullable=False),
    sa.Column('total_tasks_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['block_plans.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['railway_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocks_block_code'), 'blocks', ['block_code'], unique=True)
    op.create_index(op.f('ix_blocks_id'), 'blocks', ['id'], unique=False)
    op.create_index(op.f('ix_blocks_requested_end_time'), 'blocks', ['requested_end_time'], unique=False)
    op.create_index(op.f('ix_blocks_requested_start_time'), 'blocks', ['requested_start_time'], unique=False)
    op.create_index(op.f('ix_blocks_status'), 'blocks', ['status'], unique=False)
    op.create_table('defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_code', sa.String(length=50), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('defect_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('reported_by_system', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('calculated_priority_score', sa.Float(), nullable=True),
    sa.Column('speed_restriction_imposed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['railway_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defects_calculated_priority_score'), 'defects', ['calculated_priority_score'], unique=False)
    op.create_index(op.f('ix_defects_defect_code'), 'defects', ['defect_code'], unique=True)
    op.create_index(op.f('ix_defects_id'), 'defects', ['id'], unique=False)
    op.create_index(op.f('ix_defects_reported_at'), 'defects', ['reported_at'], unique=False)
    op.create_index(op.f('ix_defects_severity'), 'defects', ['severity'], unique=False)
    op.create_index(op.f('ix_defects_status'), 'defects', ['status'], unique=False)
    op.create_table('what_if_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('baseline_plan_id', sa.Integer(), nullable=True),
    sa.Column('simulated_parameters', sa.JSON(), nullable=False),
    sa.Column('result_metrics', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['baseline_plan_id'], ['block_plans.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_what_if_scenarios_id'), 'what_if_scenarios', ['id'], unique=False)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('alternative_number', sa.Integer(), nullable=True),
    sa.Column('strategy_name', sa.String(length=100), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('throughput_score', sa.Float(), nullable=True),
    sa.Column('delay_impact_minutes', sa.Integer(), nullable=True),
    sa.Column('multi_dept_synergy_score', sa.Float(), nullable=True),
    sa.Column('rationale_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_recommendations_id'), 'ai_recommendations', ['id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('role_at_review', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['block_plans.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_index(op.f('ix_approvals_reviewed_at'), 'approvals', ['reviewed_at'], unique=False)
    op.create_table('conflicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id_1', sa.Integer(), nullable=False),
    sa.Column('block_id_2', sa.Integer(), nullable=True),
    sa.Column('train_id', sa.Integer(), nullable=True),
    sa.Column('conflict_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_suggestion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['block_id_1'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['block_id_2'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflicts_detected_at'), 'conflicts', ['detected_at'], unique=False)
    op.create_index(op.f('ix_conflicts_id'), 'conflicts', ['id'], unique=False)
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('required_track_possession', sa.Boolean(), nullable=True),
    sa.Column('required_power_block', sa.Boolean(), nullable=True),
    sa.Column('required_traffic_block', sa.Boolean(), nullable=True),
    sa.Column('min_resources_needed', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['railway_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_tasks_id'), 'maintenance_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_status'), 'maintenance_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_tasks_task_code'), 'maintenance_tasks', ['task_code'], unique=True)
    op.create_table('train_delays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=False),
    sa.Column('cause', sa.String(length=200), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['railway_sections.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_delays_id'), 'train_delays', ['id'], unique=False)
    op.create_index(op.f('ix_train_delays_recorded_at'), 'train_delays', ['recorded_at'], unique=False)
    op.create_table('block_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=True),
    sa.Column('allocated_start_time', sa.DateTime(), nullable=False),
    sa.Column('allocated_end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_tasks_id'), 'block_tasks', ['id'], unique=False)
    op.create_table('resource_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_assignments_id'), 'resource_assignments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_assignments_id'), table_name='resource_assignments')
    op.drop_table('resource_assignments')
    op.drop_index(op.f('ix_block_tasks_id'), table_name='block_tasks')
    op.drop_table('block_tasks')
    op.drop_index(op.f('ix_train_delays_recorded_at'), table_name='train_delays')
    op.drop_index(op.f('ix_train_delays_id'), table_name='train_delays')
    op.drop_table('train_delays')
    op.drop_index(op.f('ix_maintenance_tasks_task_code'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_status'), table_name='maintenance_tasks')
    op.drop_index(op.f('ix_maintenance_tasks_id'), table_name='maintenance_tasks')
    op.drop_table('maintenance_tasks')
    op.drop_index(op.f('ix_conflicts_id'), table_name='conflicts')
    op.drop_index(op.f('ix_conflicts_detected_at'), table_name='conflicts')
    op.drop_table('conflicts')
    op.drop_index(op.f('ix_approvals_reviewed_at'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_ai_recommendations_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_what_if_scenarios_id'), table_name='what_if_scenarios')
    op.drop_table('what_if_scenarios')
    op.drop_index(op.f('ix_defects_status'), table_name='defects')
    op.drop_index(op.f('ix_defects_severity'), table_name='defects')
    op.drop_index(op.f('ix_defects_reported_at'), table_name='defects')
    op.drop_index(op.f('ix_defects_id'), table_name='defects')
    op.drop_index(op.f('ix_defects_defect_code'), table_name='defects')
    op.drop_index(op.f('ix_defects_calculated_priority_score'), table_name='defects')
    op.drop_table('defects')
    op.drop_index(op.f('ix_blocks_status'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_requested_start_time'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_requested_end_time'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_block_code'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_asset_history_recorded_at'), table_name='asset_history')
    op.drop_index(op.f('ix_asset_history_id'), table_name='asset_history')
    op.drop_table('asset_history')
    op.drop_index(op.f('ix_train_schedules_scheduled_exit_time'), table_name='train_schedules')
    op.drop_index(op.f('ix_train_schedules_scheduled_entry_time'), table_name='train_schedules')
    op.drop_index(op.f('ix_train_schedules_id'), table_name='train_schedules')
    op.drop_table('train_schedules')
    op.drop_index(op.f('ix_block_plans_status'), table_name='block_plans')
    op.drop_index(op.f('ix_block_plans_plan_code'), table_name='block_plans')
    op.drop_index(op.f('ix_block_plans_id'), table_name='block_plans')
    op.drop_table('block_plans')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_resources_resource_code'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_availability_status'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_railway_sections_section_code'), table_name='railway_sections')
    op.drop_index(op.f('ix_railway_sections_id'), table_name='railway_sections')
    op.drop_table('railway_sections')
    op.drop_index(op.f('ix_trains_train_no'), table_name='trains')
    op.drop_index(op.f('ix_trains_priority_level'), table_name='trains')
    op.drop_index(op.f('ix_trains_is_freight'), table_name='trains')
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_integration_logs_timestamp'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_system_name'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_status'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_id'), table_name='integration_logs')
    op.drop_table('integration_logs')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_corridors_id'), table_name='corridors')
    op.drop_index(op.f('ix_corridors_code'), table_name='corridors')
    op.drop_table('corridors')
    # ### end Alembic commands ###
